# Generated by Django 3.1.6 on 2021-02-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_number', models.IntegerField()),
                ('name', models.CharField(max_length=264, unique=True)),
                ('address', models.CharField(max_length=264, unique=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
