# Generated by Django 3.1.6 on 2021-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_order_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='customer',
        ),
        migrations.AddField(
            model_name='application',
            name='tests',
            field=models.CharField(choices=[('ΥΓΕΙΑ', 'ΥΓΕΙΑ'), ('ΠΛΑΣΤΙΚΟΤΗΤΑ', 'ΠΛΑΣΤΙΚΟΤΗΤΑ'), ('ΕΙΣΚΟΜΙΣΗ ΜΗΤΡΩΝ', 'ΕΙΣΚΟΜΙΣΗ ΜΗΤΡΩΝ'), ('ΘΡΑΥΣΗ ΔΟΚΙΜΙΩΝ', 'ΘΡΑΥΣΗ ΔΟΚΙΜΙΩΝ')], max_length=200, null=True),
        ),
    ]
