# Generated by Django 3.1.6 on 2021-02-22 20:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20210222_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_list',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
