# Generated by Django 3.1.6 on 2021-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_status_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status_list',
            field=models.TextField(null=True),
        ),
    ]
