# Generated by Django 3.1.6 on 2021-02-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20210222_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date']},
        ),
    ]
