# Generated by Django 3.1.6 on 2021-02-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20210224_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date']},
        ),
    ]
